[build]
  command = "npx prisma generate && npx prisma db push --accept-data-loss && npx tsx scripts/clean.ts && npx tsx scripts/seed.ts && npx tsx scripts/scrape.ts && npm run build"
  publish = ".next"

[functions]
  included_files = ["prisma/dev.db"]
